---
- hosts: all
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  vars:
    username: myuser
  tasks:
    - name: install epel repo
      yum:
        name: epel-release
        state: latest
    - name: install nginx
      yum:
        name: nginx
        state: latest
      notify:
      - enable and start nginx
    handlers:  
    - name: enable and start nginx
      service:
        name: nginx enable and start
        enabled: yes
        state: restarted
